=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Smart/mapdef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://prj-tuning.com/mapdef"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://prj-tuning.com/mapdef">
	<xsd:complexType name="map">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string"></xsd:element>
			<xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:choice>
				<xsd:element name="pattern" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
				<xsd:element name="afterRowAxis" type="xsd:boolean" />
				<xsd:element name="afterColAxis" type="xsd:boolean" />
			</xsd:choice>
			<xsd:element name="address" type="address" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="conversion" type="conversion"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="length" type="length" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="rowAxis" type="axisref" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="colAxis" type="axisref" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="map" type="map"></xsd:element>

	<xsd:complexType name="address">
		<xsd:sequence>
			<xsd:element name="offset" type="xsd:int" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:choice maxOccurs="1" minOccurs="0">
				<xsd:element name="dpp" type="xsd:hexBinary"></xsd:element>
				<xsd:element name="dppOffset" type="xsd:int"></xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="conversion">
		<xsd:all>
			<xsd:element name="factor" type="xsd:double" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="offset" type="xsd:double" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="width" type="width" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="endianness" maxOccurs="1" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="HiLo" />
						<xsd:enumeration value="LoHi" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="signed" type="xsd:boolean" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="alt" type="conversion" minOccurs="0"></xsd:element>
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="length">
		<xsd:choice>
			<xsd:element name="hardcoded" type="xsd:integer" />
			<xsd:sequence>
				<xsd:element name="address" type="address" />
				<xsd:element name="width" type="width" maxOccurs="1"
					minOccurs="0" />
			</xsd:sequence>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="axisref">
		<xsd:sequence>
			<xsd:element type="xsd:string" name="id" maxOccurs="unbounded"
				minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="width">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1" />
			<xsd:maxInclusive value="2" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/TVUB.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>TVUB</id>
	<pattern>C2 FC XX XX E6 FD XX XX E6 FE MMXX XX C2 FF XX XX DA XX XX XX D7 XX30 FF FF</pattern>
	<pattern>E6 XX FF FF XX10 C2 FC XX XX E6 FD XX XX E6 FE MMXX XX C2 FF XX XX DA 00</pattern>
	<conversion>
		<factor>0.002667</factor>
		<endianness>LoHi</endianness>
		<width>2</width>
	</conversion>
	<rowAxis>
		<id>TVUB_AXIS</id>
	</rowAxis>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Smart/KFZW_3.smart.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFZW_3</id>
	<title>KFZW_3 - 45kw Ignition Timing</title>
	<pattern>F2 F4 XX XX F2 F5 XX XX E6 F7 10 00 E6 F1 MMXX XX 8A XX XX XX E6 F1 XX XX</pattern>
	<conversion>
		<factor>1</factor>
		<signed>true</signed>
	</conversion>
 	<rowAxis>
		<id>NISTV16</id>
	</rowAxis>
	<colAxis>
		<id>TL8V16</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/SRL12GKUB.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>SRL12GKUB</id>
	<pattern>E6 FC XX XX E6 FD XX XX C2 FE XX XX D7 40 XX XX F2 FF XX XX DA XX XX XX D7 40 XX XX F6 F4 XX XX DB 00</pattern>
	<address>
		<offset>2</offset>
		<dppOffset>6</dppOffset>
	</address>
	<conversion>
		<factor>0.75</factor>
	</conversion>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Audi/KRKTE.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KRKTE</id>
	<pattern>F2 F4 XX XX 7C 44 E0 05 70 55</pattern>
	<address>
		<offset>2</offset>
		<dppOffset>-2</dppOffset>
	</address>
	<conversion>
		<factor>0.000167</factor>
		<width>2</width>
		<endianness>LoHi</endianness>
	</conversion>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/SRL12ZUUB.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>SRL12ZUUB</id>
	<pattern>E6 FC XX XX E6 FD XX XX F2 FE XX XX F2 FF XX XX DA 00 B8 78 XX18 E6 FC MMXX XX E6 FD XX XX F2 FE XX XX F2 FF XX XX DA 00 B8 78 XX70 46 F9 7F 00 XX20 46 F9 80 FF</pattern>
	<address>
		<offset>4</offset>
	</address>
	<conversion>
		<factor>0.023438</factor>
		<endianness>LoHi</endianness>
		<width>2</width>
	</conversion>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Audi/LAMFA_COLAXIS.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>LAMFA_ROWAXIS</id>
	<pattern>F2 F4 XX XX 88 40 C2 F5 XX XX 88 50 E6 F4 MMXX XX E6 F5</pattern>
	<address>
		<offset>32</offset>
		<dppOffset>36</dppOffset>
	</address>
	<conversion>
		<factor>40</factor>
	</conversion>
	<length>
		<address>
			<offset>28</offset>
			<dppOffset>24</dppOffset>
		</address>
	</length>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Smart/F2DLDR3.smart.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>F2DLDR3</id>
	<title>F2DLDR3 - 45kw Throttle Valve Intervention Level 2</title>
	<pattern>E6 F1 XX XX 0D 02 E6 F1 XX XX F2 F5 XX XX F2 F4 MMXX XX E0 87 DA XX XX XX F7 FA XX XX 8A XX XX XX 8A XX XX XX 8A|9A XX XX XX E6 F1 MMXX XX 0D 02 E6 F1 XX XX F2 F5 $$0 DA XX60 9A XX XX XX E6 F1 XX XX 0D 02 E6 F1 XX XX F2 F5 $$0 DA</pattern>
	<conversion>
		<factor>1</factor>
		<signed>false</signed>
	</conversion>
	<colAxis>
		<id>NISTV16</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Audi/LDRXNZK_ROWAXIS.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>LDRXNZK_ROWAXIS</id>
	<pattern>9A XX XX XX C2 F4 XX XX 5C 84 88 40 E6 FC MMXX XX E6 FD XX XX</pattern>
	<address>
		<dppOffset>4</dppOffset>
	</address>
	<conversion>
		<factor>0.25</factor>
		<width>2</width>
		<endianness>LoHi</endianness>
	</conversion>
</map>
