=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Smart/mapdef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://prj-tuning.com/mapdef"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://prj-tuning.com/mapdef">
	<xsd:complexType name="map">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string"></xsd:element>
			<xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:choice>
				<xsd:element name="pattern" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
				<xsd:element name="afterRowAxis" type="xsd:boolean" />
				<xsd:element name="afterColAxis" type="xsd:boolean" />
			</xsd:choice>
			<xsd:element name="address" type="address" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="conversion" type="conversion"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="length" type="length" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="rowAxis" type="axisref" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="colAxis" type="axisref" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="map" type="map"></xsd:element>

	<xsd:complexType name="address">
		<xsd:sequence>
			<xsd:element name="offset" type="xsd:int" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:choice maxOccurs="1" minOccurs="0">
				<xsd:element name="dpp" type="xsd:hexBinary"></xsd:element>
				<xsd:element name="dppOffset" type="xsd:int"></xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="conversion">
		<xsd:all>
			<xsd:element name="factor" type="xsd:double" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="offset" type="xsd:double" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="width" type="width" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="endianness" maxOccurs="1" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="HiLo" />
						<xsd:enumeration value="LoHi" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="signed" type="xsd:boolean" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="alt" type="conversion" minOccurs="0"></xsd:element>
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="length">
		<xsd:choice>
			<xsd:element name="hardcoded" type="xsd:integer" />
			<xsd:sequence>
				<xsd:element name="address" type="address" />
				<xsd:element name="width" type="width" maxOccurs="1"
					minOccurs="0" />
			</xsd:sequence>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="axisref">
		<xsd:sequence>
			<xsd:element type="xsd:string" name="id" maxOccurs="unbounded"
				minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="width">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1" />
			<xsd:maxInclusive value="2" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Smart/KFDDK.smart.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFDDK</id>
	<title>KFDDK -</title>
	<pattern>E6 F1 XX XX 0D 02 E6 F1 XX XX F2 F5 XX XX F2 F4 MMXX XX E0 87 DA XX XX XX F7 FA XX XX 8A XX XX XX 8A XX XX XX 8A|E6 F1 MMXX XX F2 F4 $$0 F2 F5 XX XX E0 87 DA</pattern>
	<conversion>
		<factor>1</factor>
		<signed>false</signed>
	</conversion>
 	<rowAxis>
		<id>SWVREV8</id>
	</rowAxis>
	<colAxis>
		<id>NISTV16</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/SRL11OPUW.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>SRL11OPUW</id>
	<pattern>F0 D7 DA XX XX XX F0 F4 E6 FC MMXX XX E6 FD XX XX F2 FE XX XX DA</pattern>
	<address>
		<offset>4</offset>
	</address>
	<conversion>
		<width>2</width>
		<endianness>LoHi</endianness>
		<factor>0.023438</factor>
	</conversion>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Smart/KFZW.smart.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFZW</id>
	<title>KFZW - Ignition Timing</title>
	<pattern>F2 F4 XX XX F2 F5 XX XX E6 F7 10 00 E6 F1 XX XX 8A XX XX XX E6 F1 MMXX XX</pattern>
	<conversion>
		<factor>1</factor>
		<signed>true</signed>
	</conversion>
 	<rowAxis>
		<id>NISTV16</id>
	</rowAxis>
	<colAxis>
		<id>TL8V16</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Audi/MLHFM.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>MLHFM</id>
	<pattern>5C 14 D4 54 MMXX50 E6 XX FF FF F0</pattern>
	<conversion>
		<width>2</width>
		<endianness>LoHi</endianness>
		<factor>0.1</factor>
	</conversion>
	<length>
		<hardcoded>512</hardcoded>
	</length>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/KFMIOP.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFMIOP</id>
	<pattern>F0 D7 DA XX XX XX F0 F4 E6 FC MMXX XX E6 FD XX XX F2 FE XX XX DA</pattern>
	<conversion>
		<factor>0.001526</factor>
		<width>2</width>
		<endianness>LoHi</endianness>
	</conversion>
	<rowAxis>
		<id>SNM16OPUW</id>
	</rowAxis>
	<colAxis>
		<id>SRL11OPUW</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/KFLBTS.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFLBTS</id>
	<pattern>88 XX E6 FC MMXX XX E6 FD XX XX E6 FE XX XX E6 FF XX XX DA XX XX XX 08 04 XX2 5C 54 D7</pattern>
	<address>
		<dppOffset>4</dppOffset>
	</address>
	<conversion>
		<factor>0.007813</factor>
	</conversion>
	<rowAxis>
		<id>SRL12GKUW</id>
		<id>SRL12GKUB</id>
	</rowAxis>
	<colAxis>
		<id>SNM16GKUB</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Volvo/SRL12GKUW.volvo.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>SRL12GKUW</id>
	<pattern>F6 8E XX XX E6 FC XX XX E6 FD XX XX C2 FE XX50 E6 FC MMXX</pattern>
	<address>
		<dppOffset>4</dppOffset>
	</address>
	<conversion>
		<width>2</width>
		<endianness>LoHi</endianness>
		<factor>0.023438</factor>
	</conversion>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/SNM16GKUB.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>SNM16GKUB</id>
	<pattern>88 XX E6 FC MMXX XX E6 FD XX XX E6 FE XX XX E6 FF XX XX DA XX XX XX 08 04 XX2 5C 54 D7</pattern>
	<address>
		<offset>8</offset>
		<dppOffset>12</dppOffset>
	</address>
	<conversion>
		<factor>40</factor>
	</conversion>
</map>
