=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Smart/mapdef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://prj-tuning.com/mapdef"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://prj-tuning.com/mapdef">
	<xsd:complexType name="map">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string"></xsd:element>
			<xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:choice>
				<xsd:element name="pattern" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
				<xsd:element name="afterRowAxis" type="xsd:boolean" />
				<xsd:element name="afterColAxis" type="xsd:boolean" />
			</xsd:choice>
			<xsd:element name="address" type="address" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="conversion" type="conversion"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="length" type="length" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="rowAxis" type="axisref" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="colAxis" type="axisref" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="map" type="map"></xsd:element>

	<xsd:complexType name="address">
		<xsd:sequence>
			<xsd:element name="offset" type="xsd:int" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:choice maxOccurs="1" minOccurs="0">
				<xsd:element name="dpp" type="xsd:hexBinary"></xsd:element>
				<xsd:element name="dppOffset" type="xsd:int"></xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="conversion">
		<xsd:all>
			<xsd:element name="factor" type="xsd:double" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="offset" type="xsd:double" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="width" type="width" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="endianness" maxOccurs="1" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="HiLo" />
						<xsd:enumeration value="LoHi" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="signed" type="xsd:boolean" maxOccurs="1"
				minOccurs="0"></xsd:element>
			<xsd:element name="alt" type="conversion" minOccurs="0"></xsd:element>
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="length">
		<xsd:choice>
			<xsd:element name="hardcoded" type="xsd:integer" />
			<xsd:sequence>
				<xsd:element name="address" type="address" />
				<xsd:element name="width" type="width" maxOccurs="1"
					minOccurs="0" />
			</xsd:sequence>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="axisref">
		<xsd:sequence>
			<xsd:element type="xsd:string" name="id" maxOccurs="unbounded"
				minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="width">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1" />
			<xsd:maxInclusive value="2" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/LDRXN.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>LDRXN</id>
	<afterRowAxis>true</afterRowAxis>
	<conversion>
		<factor>0.023438</factor>
		<width>2</width>
		<endianness>LoHi</endianness>
	</conversion>
	<rowAxis>
		<id>LDRXN_ROWAXIS</id>
	</rowAxis>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Audi/SNM16OPUW.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>SNM16OPUW</id>
	<pattern>DB 00 E6 FC XX XX C2 FD XX XX F2 FE XX XX DA 00 XX XX F6 F4 XX XX E6 FC MMXX XX F2 FD XX XX F2 FE XX XX DA 00 XX XX </pattern>
	<pattern>F6 F4 XX XX E6 FC MMXX XX F2 FD XX XX F2 FE XX XX DA 00 XX XX F6 F4 XX XX E6 FC XX XX C2 FD XX XX DA 00</pattern>
	<conversion>
		<factor>0.250000</factor>
		<endianness>LoHi</endianness>
		<width>2</width>
		<alt>
			<factor>40</factor>
		</alt>
	</conversion>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Smart/KFLDHKO.smart.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFLDHKO</id>
	<title>KFLDHKO - Overboost Correction</title>
	<pattern>9D 04 E7 F1 XX XX F7 F1 XX XX E6 F1 MMXX XX F2 F5 XX XX F2 F4 XX XX E0 XX DA</pattern>
	<conversion>
		<factor>1</factor>
		<signed>false</signed>
	</conversion>
 	<rowAxis>
		<id>PUV08</id>
	</rowAxis>
	<colAxis>
		<id>NISTV16</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/maplocator-release/me7xmls/Smart/KFFPS.smart.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>KFFPS</id>
	<title>KFFPS - Pulsation Correction Load Calculation</title>
	<pattern>7B FF 5D 02 F2 07 XX XX F6 07 XX XX E6 F1 MMXX XX F2 F4 XX XX F2 F5 XX XX E6 F7 XX XX DA</pattern>
	<conversion>
		<factor>1</factor>
		<signed>false</signed>
	</conversion>
 	<rowAxis>
		<id>NISTV16</id>
	</rowAxis>
	<colAxis>
		<id>PSV16</id>
	</colAxis>
</map>

=== prj/me7-tools/maplocator-ui/resources/me7xmls/Audi/MLOFS.audi.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://prj-tuning.com/mapdef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://prj-tuning.com/mapdef mapdef.xsd ">
	<id>MLOFS</id>
	<pattern>E0 XX F2 XX MMXX XX E0 XX 20 XX 30 XX F2</pattern>
	<pattern>5C XX 70 XX F6 XX XX XX F2 XX XX XX 22 XX MMXX XX 8D 04</pattern>
	<conversion>
		<factor>0.1</factor>
		<width>2</width>
		<endianness>LoHi</endianness>
	</conversion>
</map>
